version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/backend/self-hosted"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7