services:
  imsy:
    image: ghcr.io/pococze/imsy:latest
    environment:
      # All data are temporarilly stored in memory, if true
      - INC_DEV_MODE=true
    restart: unless-stopped
    ports:
      - 8080:8080