// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Incident struct {
	ID           pgtype.UUID
	OrgID        pgtype.UUID
	Name         string
	NameBlindIdx pgtype.Text
	Title        string
	Severity     string
	ServiceName  string
	StartedAt    pgtype.Timestamptz
	ResolvedAt   pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
