// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const add = `-- name: Add :exec
INSERT INTO incidents (
        id, org_id, name, name_blind_idx, title, severity, service_name, started_at, resolved_at, created_by, created_at, updated_at
        ) 
    VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
        )
`

type AddParams struct {
	ID           pgtype.UUID
	OrgID        pgtype.UUID
	Name         string
	NameBlindIdx pgtype.Text
	Title        string
	Severity     string
	ServiceName  string
	StartedAt    pgtype.Timestamptz
	ResolvedAt   pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.Exec(ctx, add,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.NameBlindIdx,
		arg.Title,
		arg.Severity,
		arg.ServiceName,
		arg.StartedAt,
		arg.ResolvedAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAll = `-- name: DeleteAll :exec
DELETE FROM incidents
`

func (q *Queries) DeleteAll(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAll)
	return err
}

const deleteByID = `-- name: DeleteByID :exec
DELETE FROM incidents
WHERE id = $1
`

func (q *Queries) DeleteByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteByID, id)
	return err
}

const edit = `-- name: Edit :exec
UPDATE incidents
    SET id = $1,
    org_id = $2,
    name = $3,
    name_blind_idx = $4,
    title = $5,
    severity = $6,
    service_name = $7,
    started_at = $8,
    resolved_at = $9,
    created_by = $10,
    created_at = $11,
    updated_at = $12
WHERE id = $13
RETURNING id, org_id, name, name_blind_idx, title, severity, service_name, started_at, resolved_at, created_by, created_at, updated_at
`

type EditParams struct {
	ID           pgtype.UUID
	OrgID        pgtype.UUID
	Name         string
	NameBlindIdx pgtype.Text
	Title        string
	Severity     string
	ServiceName  string
	StartedAt    pgtype.Timestamptz
	ResolvedAt   pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ID_2         pgtype.UUID
}

func (q *Queries) Edit(ctx context.Context, arg EditParams) error {
	_, err := q.db.Exec(ctx, edit,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.NameBlindIdx,
		arg.Title,
		arg.Severity,
		arg.ServiceName,
		arg.StartedAt,
		arg.ResolvedAt,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID_2,
	)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, org_id, name, name_blind_idx, title, severity, service_name, started_at, resolved_at, created_by, created_at, updated_at FROM incidents
`

func (q *Queries) GetAll(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.NameBlindIdx,
			&i.Title,
			&i.Severity,
			&i.ServiceName,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, org_id, name, name_blind_idx, title, severity, service_name, started_at, resolved_at, created_by, created_at, updated_at FROM incidents
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id pgtype.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.NameBlindIdx,
		&i.Title,
		&i.Severity,
		&i.ServiceName,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByName = `-- name: GetByName :one
SELECT id, org_id, name, name_blind_idx, title, severity, service_name, started_at, resolved_at, created_by, created_at, updated_at FROM incidents
WHERE name_blind_idx = $1
`

func (q *Queries) GetByName(ctx context.Context, nameBlindIdx pgtype.Text) (Incident, error) {
	row := q.db.QueryRow(ctx, getByName, nameBlindIdx)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.NameBlindIdx,
		&i.Title,
		&i.Severity,
		&i.ServiceName,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
