-- +goose Up
CREATE TABLE incidents (
    -- generated UUIDv7 by Go backend
    id UUID PRIMARY KEY,
    org_id UUID NOT NULL,
    -- ? What about making the incidents's name generated by Backend automatically. Currently incident's name must be written manually.
    name VARCHAR(512) NOT NULL,
    -- hashed 'name' column
    name_blind_idx VARCHAR(512),
    title VARCHAR(512) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    CONSTRAINT chk_incidents_severity CHECK (
        severity IN (
            'critical', 'high', 'medium', 'low'
        )
    ),
    service_name VARCHAR(512) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    resolved_at TIMESTAMPTZ,
    created_by UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
